# mandatory - folder with images
source: '.source/first/source'

# optional - path and name of resulting file
# delete or leave empty ('') to save file near source folder with name output.psd
destination: 'path/to/folder/file.psd'

# mandatory - sample psd file with required parameters
template: 'C:/user/user/sample.psd'

# mandatory - if true  - generate separate files for images that have different size
#             if false - crop images to specified sample
precise: false
